### ISSUE TITLE
Missing node index

### ISSUE THREAD

**Issue by jar398** [EOL/harvester#5]
The following yields an empty page; I was hoping either for an authentication failure or a list of nodes.

    http://content.eol.org/resources/157/nodes

Looking at the code (app/controllers/nodes_controller.rb) I wonder if the resource_id parameter needs to be coerced to an integer?

    @resource = Resource.find(params[:resource_id].to_i)

as opposed to

    @resource = Resource.find(params[:resource_id])

? I don't know. This could easily be a deficit in my understanding.

**Comment by JRice** [comment]
Nope, the #find method casts the argument to an ID.

[This view](http://content.eol.org/resources/157/nodes.json) works, which
is perhaps what you were looking for.

**Comment by jar398** [comment]
excellent thanks
